# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->
The path to the solution is clear, and the implementation seems to be relatively straightforward. In the worst case, we will minimize the changes to `sf` to avoid breaking existing code. We don't expect to require changes to `dbplyr`, but this could a source of delays or modification to the plan. 
Package `rodbc` could also need some modifications, but we have already existing workarounds. 
We have not identified other external factors that could impact this project. 

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->
Etienne Racine will lead the project: refactor, develop and document; 
Edzer Pebesma will be involved in global design and change review for `sf`.

## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->
The new package `sfdbi` will be added to the the `r-spatial` GitHub organisation and will adhere to the code of conduct of the `sf` package.
The tutorials will be shared via github pages and ideally could be run on docker, rstudio.cloud, or netlify to make it easy for the community to use.
The accomplishments will be documented and andvertised on blog posts on `r-spatial.org`.

## Tools & Tech
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->
We will use GitHub actions to systematically test on linux (currently the only OS to support services on github actions). We might perform as-hoc tests for other OS when needed. 

## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->
We request US$ 6,000 for this project.

## Summary
<!--
A summary of the requirements that contextualises the costs
-->
- Refactor `sf` (2000)
- Develop `sfdbi` (2000)
- Write a tutorial and polish documentation (2000)
